<YYYY> ::= <digit> <digit> <digit> <digit>
<YY> ::= <digit> <digit>
<MM> ::= "0" [1-9] | "1" [0-2]
<DDD> ::= [0-2] <digit> <digit> | "3" [0-5] <digit> | "36" [0-6]
<DD> ::= [1-2] <digit> | "3" [0-1]
<D> ::= [1-7]
<BasicDate> ::= <YYYY> <MM> <DD></DD>
<Date> ::= <YYYY> "-" <MM> "-" <DD>
<BasicOrdinalDate> ::= <YYYY> <DDD>
<OrdinalDate> ::= <YYYY> "-" <DDD>
<HH> ::= [0-1] <digit> | "2" [0-3]
<mm> ::= [0-5] <digit>
<ss> ::= [0-5] <digit>
<SSS> ::= <digit> <digit> <digit>
<Millis> ::= <dot> <SSS>
<BasicTimeNoMillis> ::= <HH> <mm> <ss> 
<TimeNoMillis> ::= <HH> ":" <mm> ":" <ss> 
<BasicTime> ::= <BasicTimeNoMillis> <Millis>
<Time> ::= <TimeNoMillis> <Millis>
<BasicTTimeNoMillis> ::= "T" <HH> <mm> <ss>
<BasicTTime> ::= "T" <BasicTTimeNoMillis> <Millis>
<TTimeNoMillis> ::= "T" <TimeNoMillis>
<TTime> ::= <TTimeNoMillis> <Millis>
<BasicDateTimeNoMillis> ::= <BasicDate> "T" <HH> <mm> <ss>
<BasicDateTime> ::= <BasicDateTime> <Millis>
<DateTimeNoMillis> ::= <Date> "T" <TimeNoMillis>
<DateTime> ::= <DateTimeNoMillis> <Millis>
<OrdinalDateTimeNoMillis> ::= <OrdinalDate> "T" <HH> ":" <mm> ":" <ss>
<OrdinalDateTime> ::= <OrdinalDateTimeNoMillis> <Millis>
<HourMinute> ::= <HH> ":" <mm>
<HourMinuteSecond> ::= <HourMinute> ":" <ss>
<HourMinuteSecondMillis> ::= <HourMinuteSecond> "." <SSS>
<DateHour> ::= <Date> "T" <HH>
<DateHourMinute> ::= <Date>  "T" <HourMinute>
<DateHourMinuteSecond> ::= <Date>  "T" <HourMinuteSecond>
<DateHourMinuteSecondMillis> ::= <Date>  "T" <HourMinuteSecondMillis>
<YearMonth> ::= <YYYY> "-" <MM>
<YearMonthDay> ::= <YearMonth> "-" <DD>